// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdZgo_zMuI6vvGCEozJd-p7-aBH2m1j20',
    appId: '1:391480099520:web:f40efa93dfcb17420da325',
    messagingSenderId: '391480099520',
    projectId: 'login-6841f',
    authDomain: 'login-6841f.firebaseapp.com',
    storageBucket: 'login-6841f.firebasestorage.app',
    measurementId: 'G-VCGEMFBPE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgpjpNaBLVUQXSMYNDquH_VqIXj7_2L4',
    appId: '1:391480099520:android:1f3ce9f75eee200b0da325',
    messagingSenderId: '391480099520',
    projectId: 'login-6841f',
    storageBucket: 'login-6841f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0hCQy2JZ7ncxA5H_UaQD9vAeW7KjVcWI',
    appId: '1:391480099520:ios:05792ccd6f24da700da325',
    messagingSenderId: '391480099520',
    projectId: 'login-6841f',
    storageBucket: 'login-6841f.firebasestorage.app',
    iosBundleId: 'com.example.loginScreens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0hCQy2JZ7ncxA5H_UaQD9vAeW7KjVcWI',
    appId: '1:391480099520:ios:05792ccd6f24da700da325',
    messagingSenderId: '391480099520',
    projectId: 'login-6841f',
    storageBucket: 'login-6841f.firebasestorage.app',
    iosBundleId: 'com.example.loginScreens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdZgo_zMuI6vvGCEozJd-p7-aBH2m1j20',
    appId: '1:391480099520:web:41081ba067ed69de0da325',
    messagingSenderId: '391480099520',
    projectId: 'login-6841f',
    authDomain: 'login-6841f.firebaseapp.com',
    storageBucket: 'login-6841f.firebasestorage.app',
    measurementId: 'G-J8R7KM4257',
  );
}
